FROM node:12
# Create app directory
WORKDIR /data/app

COPY package*.json ./

RUN npm install

RUN npm install pm2 -g
# 拷贝应用程序
COPY app.js .

# 暴露端口
EXPOSE 8080
ENV SYSNAME=MY_APP
# 运行命令
CMD ["pm2-runtime", "app.js"]